esphome:
  name: esphome-web-959f0c
  friendly_name: ESPHome Web 959f0c
  libraries:
    - "Wire"
  includes:
    - aquaping.h

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lLMeWIgrkYPBowNcOJCqozLmoet2lHxsPcFlaDZEIW8="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-959F0C"
    password: "0GxUZfPAtwiX"

captive_portal:

binary_sensor:
- platform: gpio
  pin: D3
  name: "AquaPing Noise Alert"
  id: noise
  icon: "mdi:volume-vibrate"
 
- platform: gpio
  pin: D4
  name: "AquaPing Leak Alert"
  id: leak
  icon: "mdi:water-pump"
  
# Not all of the retrieved data is displayed
sensor:
- platform: custom
  lambda: |-
    auto aquaping = new AquaPing();
    App.register_component(aquaping);
    return {aquaping->quiet_count,aquaping->leak_count,aquaping->noise_count,aquaping->polling_period,aquaping->event_array_size,aquaping->trigger_threshold,aquaping->background_array_size};

  sensors:
  - name: "Quiet Count Display" 
  - name: "Leak Count Display"
  - name: "Noise Count Display"
  - name: "Polling Period Display"  
  - name: "Event Size Display" 
  - name: "Trigger Threshold Display" 
  - name: "Background Set Size Display" 

number:
  - platform: template
    name: "Event array size"
    optimistic: true
    min_value: 10
    max_value: 255
    initial_value: 20
    step: 1
    mode: box
    id: event_input
    icon: "mdi:counter"

  - platform: template
    name: "Alarm trigger size"
    optimistic: true
    min_value: 10
    max_value: 255
    initial_value: 18
    step: 1
    mode: box
    id: trigger_input
    icon: "mdi:counter"

  - platform: template
    name: "Background array size"
    optimistic: true
    min_value: 10
    max_value: 255
    initial_value: 30
    step: 1
    mode: box
    id: background_input
    icon: "mdi:counter"

  - platform: template
    name: "Polling period"
    optimistic: true
    min_value: 1
    max_value: 9
    initial_value: 2
    step: 1
    mode: box
    id: polling_input
    icon: "mdi:timer-sand"
  
    
switch:
  - platform: template
    name: "LED Switch"
    restore_mode: ALWAYS_ON #8266 ignores this
    id: led
    icon: "mdi:led-outline"
    optimistic: true

  
  

    
